sudo: required
dist: bionic
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    # Install clang-6.0 on the side as the default
    # does not have the gold linker
    packages:
      - clang-6.0
      - llvm-6.0-dev
env:
  - CMAKE_BUILD_TYPE=Release
install:
  - sudo apt-get install -qq libboost-all-dev liblpsolve55-dev lp-solve
  - sudo apt-get install -qq --force-yes libeigen3-dev
  # Force usage of installed clang, and not default
  - if [ "$CC" = "clang" ]; then export CXX="/usr/bin/clang++-6.0" CC="/usr/bin/clang-6.0"; fi
script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
  - make -j2 VERBOSE=1
  - ctest -V -j2
branches:
  only:
    - master
    - test
notifications:
  email: false
