language: cpp
compiler:
    - gcc
    - clang
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:apokluda/boost1.53 -y
  - sudo apt-get update -qq
  - sudo apt-get install libboost1.53-dev libboost-test1.53-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest -v
branches:
  only:
    - master
notifications:
    email: false
